name: Daily HTML Build

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:
  
permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Generate HTML
        run: |
          python generate_html.py
      - name: Commit and Push
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add site/
          git commit -m "Daily update" || echo "Nothing to commit"
          git push
